
name: basmati-forecast
on:
  schedule:
    - cron: '30 3 * * *'   # 03:30 UTC ~= 09:00 IST
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install -r requirements.txt
      - run: . .venv/bin/activate && python cli.py run-all --horizons 7 30 180
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts/**
